name: Sync Develop with Main

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main' # Explicitly checkout main branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create develop branch if it doesn't exist
        run: |
          git checkout develop
          git fetch origin main
          git merge main

      - name: Force-push changes to develop branch
        run: |
          git push --force origin develop
